name: Node.js CI/CD to AWS EC2 (Ubuntu)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./

    - name: Run tests (Example)
      run: npm test
      working-directory: ./
      continue-on-error: true

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          FORKED_REPO_URL="https://github.com/Ejiwumiabdulhamid79/ci-cd-nodejs-aws-ec2"
          FORKED_REPO_NAME="ci-cd-nodejs-aws-ec2"

           # Construct the directory path on the EC2 instance
          APP_DIRECTORY="/home/ubuntu/$FORKED_REPO_NAME"
          
          # Check if the app directory exists; clone if it doesn't
           if [ ! -d "$APP_DIRECTORY" ]; then
            echo "Cloning repository..."
            git clone "$FORKED_REPO_URL" "$APP_DIRECTORY"
          else
            echo "Repository exists, pulling latest changes..."
          fi

          cd "$APP_DIRECTORY"

          # Update package lists
          sudo apt update

          # Install Node.js and npm (pm2 will be installed via npm)
          sudo apt install -y nodejs npm

          # Install pm2 globally using npm
          sudo npm install -g pm2

          # Verify pm2 installation
          if ! command -v pm2 &> /dev/null; then
            echo "pm2 installation failed!"
            exit 1
          fi

          git pull origin master
          npm install
          pm2 restart server.js || pm2 start server.js --name app
