name: Node.js CI/CD to AWS EC2 (Ubuntu)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./

    - name: Run tests (Example)
      run: npm test
      working-directory: ./
      continue-on-error: true

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ubuntu  #  <-- Changed to 'ubuntu'
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/nodejs-cicd-aws-ec2  # <-- Changed user to ubuntu
          sudo apt update -y  # <-- Added update command
          sudo apt install -y nodejs npm pm2  # <-- Added package installation
          git pull origin main
          npm install
          pm2 restart app.js || pm2 start app.js --name app
