name: Node.js CI/CD to AWS EC2 (Ubuntu)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./

    - name: Run tests (Example)
      run: npm test
      working-directory: ./
      continue-on-error: true

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
         # --- DEBUGGING ONLY - START ---
           echo "Current directory: $(pwd)"
           echo "Listing /home/ubuntu:"
           ls -la /home/ubuntu
           echo "Listing /home/ubuntu/ci-cd-nodejs-aws-ec2:" # Use the *expected* directory name
           ls -la /home/ubuntu/ci-cd-nodejs-aws-ec2
           echo "Attempting to start server.js directly (will likely fail, but shows path):"
           node /home/ubuntu/ci-cd-nodejs-aws-ec2/server.js  # Try to run directly (expect failure)
           # --- DEBUGGING ONLY - END --- 
